'use strict';
const express = require("express");
const routes = express.Router();
const UserController = require('./controllers/UserController');
const ProfController = require('./controllers/ProfsController');
const LoginController = require('./controllers/LoginController');
const PasswordRecover = require('./controllers/RecoverController');
const temposController = require('./controllers/temposController');
const disciplinaController = require('./controllers/disciplinaController');
const versionsController = require('./controllers/versionsController');
const salaController = require('./controllers/salaController');
const turmaController = require('./controllers/TurmaController');
const authNormalUser = require('./middleware/normalAuth');
const adminAuth = require('./middleware/adminAuth');
routes.post('/login', LoginController.index);
routes.post('/version', versionsController.search);
routes.post('/recover', PasswordRecover.index);
routes.use(authNormalUser);
routes.post('/checkToken', LoginController.search);
routes.post('/qrcode', temposController.search);
routes.use(adminAuth);
routes.post('/users', UserController.store);
routes.post('/prof', ProfController.store);
routes.post('/disciplina', disciplinaController.store);
routes.post('/sala', salaController.novaSala);
routes.post('/horario', salaController.horario);
routes.post('/turma', turmaController.store);
routes.post('/editTurma', turmaController.update);
routes.post('/editSala', salaController.update);
routes.post('/editDisciplina', disciplinaController.update);
routes.post('/editProfs', ProfController.update);
module.exports = routes;